var CREATE_ROUTINE_TABLE = `
CREATE TABLE IF NOT EXISTS routine
( id INTEGER PRIMARY KEY AUTOINCREMENT
, name TEXT UNIQUE
, created INTEGER
);
`;

var CREATE_TICKOFF_TABLE = `
CREATE TABLE IF NOT EXISTS tickoff
( id INTEGER PRIMARY KEY AUTOINCREMENT
, routine INTEGER
, date INTEGER
, comment TEXT
);
`;